/**
 * Shared mock for the 'lucide' module.
 *
 * Provides mock exports matching the icons imported in lucide_icons.ts.
 * Test files can use: vi.mock('lucide', () => lucideMock)
 */

import { vi } from 'vitest';

const icon = ['svg', {}, []] as const;

export const lucideMock: Record<string, unknown> = {
  createIcons: vi.fn(),
  icons: {},
  AlertCircle: icon,
  Archive: icon,
  ArchiveX: icon,
  ArrowLeft: icon,
  ArrowRight: icon,
  Asterisk: icon,
  AtSign: icon,
  BarChart2: icon,
  BarChart3: icon,
  BookOpen: icon,
  BookOpenCheck: icon,
  BookOpenText: icon,
  Brush: icon,
  Calculator: icon,
  Check: icon,
  ChevronDown: icon,
  ChevronLeft: icon,
  ChevronRight: icon,
  ChevronsLeft: icon,
  ChevronsRight: icon,
  Circle: icon,
  CircleAlert: icon,
  CircleCheck: icon,
  CircleChevronLeft: icon,
  CircleChevronRight: icon,
  CircleDot: icon,
  CircleHelp: icon,
  CircleMinus: icon,
  CirclePlus: icon,
  CircleX: icon,
  Clock: icon,
  Database: icon,
  Download: icon,
  Eraser: icon,
  ExternalLink: icon,
  Eye: icon,
  FastForward: icon,
  FileDown: icon,
  FilePen: icon,
  FilePenLine: icon,
  FileStack: icon,
  Filter: icon,
  FilterX: icon,
  Frown: icon,
  HelpCircle: icon,
  Image: icon,
  Key: icon,
  Languages: icon,
  Layers: icon,
  Lightbulb: icon,
  LightbulbOff: icon,
  Link: icon,
  Loader: icon,
  Loader2: icon,
  Lock: icon,
  LogIn: icon,
  LogOut: icon,
  Mail: icon,
  Minus: icon,
  Notebook: icon,
  NotebookPen: icon,
  NotepadText: icon,
  NotepadTextDashed: icon,
  Palette: icon,
  Pencil: icon,
  Plus: icon,
  Printer: icon,
  RefreshCw: icon,
  Repeat: icon,
  Rewind: icon,
  Rss: icon,
  Search: icon,
  Send: icon,
  Server: icon,
  Settings: icon,
  Shield: icon,
  Sliders: icon,
  SlidersHorizontal: icon,
  Smile: icon,
  Square: icon,
  SquareCheckBig: icon,
  SquareMinus: icon,
  SquarePen: icon,
  SquarePlus: icon,
  Star: icon,
  StickyNote: icon,
  Sun: icon,
  ThumbsUp: icon,
  Upload: icon,
  User: icon,
  UserPlus: icon,
  Volume2: icon,
  VolumeX: icon,
  Wand2: icon,
  WrapText: icon,
  X: icon,
  XCircle: icon,
  Zap: icon,
};
