<?php

/**
 * Database Wizard Service - Business logic for database connection wizard
 *
 * PHP version 8.1
 *
 * @category Lwt
 * @package  Lwt\Services
 * @author   HugoFara <hugo.farajallah@protonmail.com>
 * @license  Unlicense <http://unlicense.org/>
 * @link     https://hugofara.github.io/lwt/docs/php/
 * @since    3.0.0
 */

namespace Lwt\Services;

/**
 * Database connection configuration object.
 *
 * @category Lwt
 * @package  Lwt\Services
 * @author   HugoFara <hugo.farajallah@protonmail.com>
 * @license  Unlicense <http://unlicense.org/>
 * @link     https://hugofara.github.io/lwt/docs/php/
 * @since    3.0.0
 */
class DatabaseConnection
{
    /**
     * @var string Server name
     */
    public string $server;

    /**
     * @var string User ID
     */
    public string $userid;

    /**
     * @var string Password for this user
     */
    public string $passwd;

    /**
     * @var string Database name
     */
    public string $dbname;

    /**
     * @var string Socket to use
     */
    public string $socket;

    /**
     * Build a new connection object.
     *
     * @param string $server Server name
     * @param string $userid User ID
     * @param string $passwd Password for this user
     * @param string $dbname Database name
     * @param string $socket Socket to use
     */
    public function __construct(
        string $server = "",
        string $userid = "",
        string $passwd = "",
        string $dbname = "",
        string $socket = ""
    ) {
        $this->server = $server;
        $this->userid = $userid;
        $this->passwd = $passwd;
        $this->dbname = $dbname;
        $this->socket = $socket;
    }

    /**
     * Load data from a .env file.
     *
     * @param string $file_name .env file to load data from.
     *
     * @return void
     */
    public function loadFile(string $file_name): void
    {
        if (!file_exists($file_name)) {
            return;
        }
        $lines = file($file_name, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        foreach ($lines as $line) {
            if (strpos(trim($line), '#') === 0) {
                continue;
            }
            if (strpos($line, '=') === false) {
                continue;
            }
            list($key, $value) = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);
            switch ($key) {
                case 'DB_HOST':
                    $this->server = $value;
                    break;
                case 'DB_USER':
                    $this->userid = $value;
                    break;
                case 'DB_PASSWORD':
                    $this->passwd = $value;
                    break;
                case 'DB_NAME':
                    $this->dbname = $value;
                    break;
                case 'DB_SOCKET':
                    $this->socket = $value;
                    break;
            }
        }
    }

    /**
     * Connection as an .env formatted string.
     *
     * @return string .env string representing connection details
     */
    public function getAsText(): string
    {
        $content = "# LWT Database Configuration\n";
        $content .= "# Generated by Database Connection Wizard\n\n";
        $content .= "DB_HOST=" . $this->server . "\n";
        $content .= "DB_USER=" . $this->userid . "\n";
        $content .= "DB_PASSWORD=" . $this->passwd . "\n";
        $content .= "DB_NAME=" . $this->dbname . "\n";
        if (!empty($this->socket)) {
            $content .= "DB_SOCKET=" . $this->socket . "\n";
        }
        return $content;
    }
}

/**
 * Service class for database connection wizard operations.
 *
 * @category Lwt
 * @package  Lwt\Services
 * @author   HugoFara <hugo.farajallah@protonmail.com>
 * @license  Unlicense <http://unlicense.org/>
 * @link     https://hugofara.github.io/lwt/docs/php/
 * @since    3.0.0
 */
class DatabaseWizardService
{
    /**
     * Path to the .env file.
     *
     * @var string
     */
    private string $envPath;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->envPath = __DIR__ . '/../../../.env';
    }

    /**
     * Check if .env file exists.
     *
     * @return bool True if file exists
     */
    public function envFileExists(): bool
    {
        return file_exists($this->envPath);
    }

    /**
     * Get .env file path.
     *
     * @return string Path to .env file
     */
    public function getEnvPath(): string
    {
        return $this->envPath;
    }

    /**
     * Load connection from .env file.
     *
     * @return DatabaseConnection Connection object
     */
    public function loadConnection(): DatabaseConnection
    {
        $conn = new DatabaseConnection();
        $conn->loadFile($this->envPath);
        return $conn;
    }

    /**
     * Create a new empty connection.
     *
     * @return DatabaseConnection Empty connection object
     */
    public function createEmptyConnection(): DatabaseConnection
    {
        return new DatabaseConnection();
    }

    /**
     * Save connection to .env file.
     *
     * @param DatabaseConnection $conn Connection to save
     *
     * @return void
     */
    public function saveConnection(DatabaseConnection $conn): void
    {
        $handle = fopen($this->envPath, 'w');
        fwrite($handle, $conn->getAsText());
        fclose($handle);
    }

    /**
     * Autocomplete connection with server defaults.
     *
     * @return DatabaseConnection Pre-filled connection object
     */
    public function autocompleteConnection(): DatabaseConnection
    {
        return new DatabaseConnection(
            $_SERVER['SERVER_ADDR'] ?? 'localhost',
            "",
            "",
            $_SERVER['SERVER_NAME'] ?? 'lwt',
            ""
        );
    }

    /**
     * Test a database connection.
     *
     * @param DatabaseConnection $conn Connection to test
     *
     * @return string Status message
     */
    public function testConnection(DatabaseConnection $conn): string
    {
        $mysqli = mysqli_init();
        if ($mysqli === false) {
            return "MySQL is not accessible!";
        }

        try {
            if ($conn->socket != "") {
                $success = mysqli_real_connect(
                    $mysqli,
                    $conn->server,
                    $conn->userid,
                    $conn->passwd,
                    $conn->dbname,
                    socket: $conn->socket
                );
            } else {
                $success = mysqli_real_connect(
                    $mysqli,
                    $conn->server,
                    $conn->userid,
                    $conn->passwd,
                    $conn->dbname
                );
            }

            if (!$success) {
                return "Can't connect!";
            } elseif (mysqli_errno($mysqli) != 0) {
                return "ERROR: " . mysqli_error($mysqli) .
                    " error number: " . mysqli_errno($mysqli);
            }

            return "Connection established with success!";
        } catch (\Exception $except) {
            return (string)$except;
        }
    }

    /**
     * Create connection from form data.
     *
     * @param array $formData Form input data
     *
     * @return DatabaseConnection Connection object
     */
    public function createConnectionFromForm(array $formData): DatabaseConnection
    {
        return new DatabaseConnection(
            $formData['server'] ?? '',
            $formData['userid'] ?? '',
            $formData['passwd'] ?? '',
            $formData['dbname'] ?? '',
            $formData['socket'] ?? ''
        );
    }
}
