name: Build and push Docker images

on:
  push:
    branches: [ 'master' ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SUPPORTED_PLATFORMS: 'linux/amd64,linux/arm/v7,linux/arm64,linux/mips64le,linux/s390x'
  # Note: rarer platforms. Not a real array since it starts with ","
  ADDITIONAL_PLATFORMS: ${{ github.event_name == 'release' && ',linux/386,linux/arm/v5,linux/ppc64le' || '' }}

jobs:
  build-and-push-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.SUPPORTED_PLATFORMS }}${{ env.ADDITIONAL_PLATFORMS }}
        

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ env.SUPPORTED_PLATFORMS }}${{ env.ADDITIONAL_PLATFORMS }} 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
